# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("category.proto", :syntax => :proto3) do
    add_message "pb.Blank" do
    end
    add_message "pb.Category" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
    end
    add_message "pb.CategoryResponse" do
      optional :category, :message, 1, "pb.Category"
    end
    add_message "pb.CreateCategoryRequest" do
      optional :name, :string, 1
      optional :description, :string, 2
    end
    add_message "pb.CategoryList" do
      repeated :categories, :message, 1, "pb.Category"
    end
    add_message "pb.CategoryGetRequest" do
      optional :id, :string, 1
    end
  end
end

module Pb
  Blank = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Blank").msgclass
  Category = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Category").msgclass
  CategoryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CategoryResponse").msgclass
  CreateCategoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CreateCategoryRequest").msgclass
  CategoryList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CategoryList").msgclass
  CategoryGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CategoryGetRequest").msgclass
end
